Migrate from Travis to GitHub Actions (#354)
This PR removes the travis script and replaces it by a GitHub Actions workflow script, as in 2021 Travis stopped giving access to its CI resources to open source projects for free.

diff --git a/.github/workflows/build-PR.yml b/.github/workflows/build-PR.yml
--- a/.github/workflows/build-PR.yml
+++ b/.github/workflows/build-PR.yml
@@ -1,4 +1,4 @@
-name: Build PR
+name: Build and Test
 
 on:
   push:
@@ -7,25 +7,56 @@ on:
   pull_request:
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
+  unix:
+    strategy:
+      matrix:
+        os: [ubuntu, macos]
+        compiler: [g++, clang++]
+        exclude:
+          - os: macos
+            compiler: g++
 
+    name: ${{matrix.os}} (${{matrix.compiler}})
+
+    runs-on: ${{matrix.os}}-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
       - name: Install dependencies
+        shell: bash
         run: |
-            sudo apt-get update
-            sudo apt-get install --yes cmake gcc
-            sudo apt-get install --yes libfreetype6-dev libpng++-dev zlib1g-dev libunittest++-dev libfontconfig1-dev
+            if [ "$RUNNER_OS" == "Linux" ]; then
+                sudo apt-get update
+                sudo apt-get install --yes libpng++-dev libunittest++-dev
+                sudo apt-get install --yes fonts-noto-cjk
+            elif [ "$RUNNER_OS" == "macOS" ]; then
+                brew install unittest-cpp
+                brew tap homebrew/cask-fonts
+                brew install --cask font-noto-sans-cjk 
+            else
+                echo "$RUNNER_OS not supported"
+                exit 1
+            fi
 
       - name: Build
+        shell: bash
         run: |
-            export CC=$COMPILER
-            export CXX=${CC/gcc/g++}
-            export CXX=${CXX/clang/clang++}
+            export CXX=${{matrix.compiler}}
             $CXX --version
             mkdir build && cd build
-            cmake -G "Unix Makefiles" ..
+            cmake -G "Unix Makefiles" -DLOMSE_RUN_TESTS=OFF ..
             make
+
+      - name: Run tests
+        shell: bash
+        run: |
+            cd build
             ./testlib
+
+#      - name: Upload logs on fail
+#        if: ${{ failure() }}
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: Build failure logs
+#          path: ${{ runner.temp }}/build_logs
